<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-PQ7S2JC" failures="1" tests="6" name="Surefire test" time="188.722" errors="0" timestamp="2023-05-02T17:51:19 IST">
  <testcase classname="appiumproject.testcases.Test01_GeneralStore" name="GeneralStoreTest01" time="30.437"/>
  <testcase classname="appiumproject.testcases.Test02_MultipleTests" name="VerifyNameValidation_Test01" time="13.867">
    <failure type="java.lang.AssertionError" message="expected [Please enter your nameeeeeee] but found [Please enter your name]">
      <![CDATA[java.lang.AssertionError: expected [Please enter your nameeeeeee] but found [Please enter your name]
at appiumproject.testcases.Test02_MultipleTests.VerifyNameValidation_Test01(Test02_MultipleTests.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- VerifyNameValidation_Test01 -->
  <testcase classname="appiumproject.testcases.Test02_MultipleTests" name="FormSubmit_Test02" time="14.499"/>
  <testcase classname="appiumproject.testcases.Test03_DDTByDataProvider" name="DDTByDataProviderTest03" time="17.179"/>
  <testcase classname="appiumproject.testcases.Test04_DDTByJason" name="DDTByJasonFile04" time="10.311"/>
  <testcase classname="appiumproject.testcases.Test04_DDTByJason" name="DDTByJasonFile04" time="17.458"/>
</testsuite> <!-- Surefire test -->
